### ISSUE TITLE
Update losses via API

### ISSUE THREAD

**Issue by melissajstudent** [melissajstudent/koth#16]
Pull scores from an NFL API service and update pick.loss. I've signed up for and have a key for SportRadar.

- Implement Games model
- Populate Games model from SportRadar API
   - initially using Schedule endpoint (1x)
   - weekly update score using GameBoxScore
- Update Picks model to associate with Games model
- Add logic that sets loss = true when picked team score less than opposing team

[SportRadar NFL API](http://developer.sportradar.us/page/NFL_Official)

| Model attribute   | type  | Endpoint | API field |
| ----------- | ----- | ----- | ------|
| nfl_week      | int        | Schedule | weeks:sequence   |
| game_id      | string   | Schedule | weeks:games:id |
| scheduled |  datetime | Schedule | weeks:games:scheduled |
| utc-offset  | int | Schedule | weeks:games:utc_offset |
| home_team_name | string | Schedule | weeks:games:home:name |
| away_team_name  | string  | Schedule | weeks:games:away:name |
| home_team_score | int | Game Boxscore | summary:home:points |
| away_team_score | int | Game Boxscore | summary:away:points |

Sample Schedule endpoint response

```
{
"id": "49037b4f-71c4-4e4d-8963-4f9b83e0b4bc"
"year": 2016
"type": "REG"
"name": "REG"
"weeks": [17]
0:  {
    "id": "fca6b835-3977-4979-8a74-4d3f46e3be24"
    "sequence": 1
    "title": "1"
    "games": [16]
        0:  {
        "id": "28290722-4ceb-4a4c-a4e5-1f9bec7283b3"
        "status": "closed"
        "reference": "56905"
        "number": 5
        "scheduled": "2016-09-11T17:00:00+00:00"
        "attendance": 63179
        "utc_offset": -5
        "entry_mode": "INGEST"
        "weather": "Temp: 90 F, Humidity: 55%, Wind: N 3 mph"
        "venue": {
            "id": "4c5c036d-dd3d-4183-b595-71a43a97560f"
            "name": "EverBank Field"
            "city": "Jacksonville"
            "state": "FL"
            "country": "USA"
            "zip": "32202"
            "address": "One EverBank Field Drive"
            "capacity": 67246
            "surface": "turf"
            "roof_type": "outdoor"
        }-
        "home": {
            "name": "Jacksonville Jaguars"
            "alias": "JAC"
            "game_number": 1
            "id": "f7ddd7fa-0bae-4f90-bc8e-669e4d6cf2de"
        }-
        "away": {
            "name": "Green Bay Packers"
            "alias": "GB"
            "game_number": 1
            "id": "a20471b4-a8d9-40c7-95ad-90cc30e46932"
        }-
        "broadcast": {
        "network": "FOX"
        }-
    }-
1:  {
    "id": "3b1521d9-ec2c-48e9-b695-c493e65470b1"
    "status": "closed"
    "reference": "56910"
    "number": 10
    "scheduled": "2016-09-11T17:00:00+00:00"
    "attendance": 63816
    "utc_offset": -6
    "entry_mode": "INGEST"
    "weather": "Sunny Temp: 76 F, Humidity: 47%, Wind: East 5 mph"
    "venue": {
        "id": "5295c1b7-c85c-49cb-9569-1707c65324e5"
        "name": "Nissan Stadium"
        "city": "Nashville"
        "state": "TN"
        "country": "USA"
        "zip": "37213"
        "address": "One Titans Way"
        "capacity": 69143
        "surface": "turf"
        "roof_type": "outdoor"
    }-
    "home": {
        "name": "Tennessee Titans"
        "alias": "TEN"
        "game_number": 1
        "id": "d26a1ca5-722d-4274-8f97-c92e49c96315"
    }-
    "away": {
        "name": "Minnesota Vikings"
        "alias": "MIN"
        "game_number": 1
        "id": "33405046-04ee-4058-a950-d606f8c30852"
    }-
    "broadcast": {
        "network": "FOX"
    }-
}
```

Game BoxScore example response. 

[game_boxscore_response-export.txt](https://github.com/melissajstudent/koth/files/494397/game_boxscore_response-export.txt)

**Comment by melissajstudent** [comment]
Found some good documentation here: http://www.rubydoc.info/gems/sports_data_api/0.2.4/SportsDataApi/Nfl#boxscore-class_method

Played in rails c tonight and entered the following:
`SportsDataApi.set_access_level(:nfl, 'ot')`

`SportsDataApi.set_key(:nfl, '<MY API KEY HERE>')`

`scores = SportsDataApi::Nfl::Game.boxscore(2016, 'reg', 1, 'JAC', 'GB', 1)`

but received, `NoMethodError: undefined method 'boxscore' for SportsDataApi::Nfl::Game:Class`

I'll give it another try tomorrow

**Comment by wonderwoman13** [comment]
@melissajstudent I've got the schedule import working 💃 I'd like to review it on our call on Monday. The API definitely has a throttle to it (can only hit it so many times within a minute) so we'll need to discuss collecting scores.
